// app/_data/englishWords.ts

export type EnglishWord = {
  word: string;
  meaning: string;
  pos: "noun" | "verb" | "adjective" | "preposition";
};

/**
 * 小学5・6年生向け 英単語バンク（120語）
 * ・意味は小学生語彙
 * ・中学英語に接続しやすい
 */
export const ENGLISH_WORDS_G56: EnglishWord[] = [
  // ===== noun（30）=====
  { word: "apple", meaning: "りんご", pos: "noun" },
  { word: "book", meaning: "本", pos: "noun" },
  { word: "school", meaning: "学校", pos: "noun" },
  { word: "friend", meaning: "友だち", pos: "noun" },
  { word: "teacher", meaning: "先生", pos: "noun" },
  { word: "student", meaning: "生徒", pos: "noun" },
  { word: "family", meaning: "家族", pos: "noun" },
  { word: "home", meaning: "家", pos: "noun" },
  { word: "house", meaning: "家（建物）", pos: "noun" },
  { word: "room", meaning: "部屋", pos: "noun" },
  { word: "desk", meaning: "机", pos: "noun" },
  { word: "chair", meaning: "いす", pos: "noun" },
  { word: "pen", meaning: "ペン", pos: "noun" },
  { word: "pencil", meaning: "えんぴつ", pos: "noun" },
  { word: "bag", meaning: "かばん", pos: "noun" },
  { word: "bookstore", meaning: "本屋", pos: "noun" },
  { word: "library", meaning: "図書館", pos: "noun" },
  { word: "music", meaning: "音楽", pos: "noun" },
  { word: "game", meaning: "ゲーム", pos: "noun" },
  { word: "sport", meaning: "スポーツ", pos: "noun" },
  { word: "soccer", meaning: "サッカー", pos: "noun" },
  { word: "baseball", meaning: "野球", pos: "noun" },
  { word: "food", meaning: "食べ物", pos: "noun" },
  { word: "water", meaning: "水", pos: "noun" },
  { word: "milk", meaning: "牛乳", pos: "noun" },
  { word: "bread", meaning: "パン", pos: "noun" },
  { word: "rice", meaning: "ごはん", pos: "noun" },
  { word: "time", meaning: "時間", pos: "noun" },
  { word: "day", meaning: "日", pos: "noun" },
  { word: "night", meaning: "夜", pos: "noun" },

  // ===== verb（40）=====
  { word: "eat", meaning: "食べる", pos: "verb" },
  { word: "drink", meaning: "飲む", pos: "verb" },
  { word: "go", meaning: "行く", pos: "verb" },
  { word: "come", meaning: "来る", pos: "verb" },
  { word: "get", meaning: "手に入れる", pos: "verb" },
  { word: "give", meaning: "あげる", pos: "verb" },
  { word: "see", meaning: "見る", pos: "verb" },
  { word: "watch", meaning: "（注意して）見る", pos: "verb" },
  { word: "look", meaning: "見る（目を向ける）", pos: "verb" },
  { word: "read", meaning: "読む", pos: "verb" },
  { word: "write", meaning: "書く", pos: "verb" },
  { word: "listen", meaning: "聞く", pos: "verb" },
  { word: "speak", meaning: "話す", pos: "verb" },
  { word: "say", meaning: "言う", pos: "verb" },
  { word: "tell", meaning: "伝える", pos: "verb" },
  { word: "ask", meaning: "たずねる", pos: "verb" },
  { word: "answer", meaning: "答える", pos: "verb" },
  { word: "run", meaning: "走る", pos: "verb" },
  { word: "walk", meaning: "歩く", pos: "verb" },
  { word: "play", meaning: "遊ぶ", pos: "verb" },
  { word: "study", meaning: "勉強する", pos: "verb" },
  { word: "learn", meaning: "学ぶ", pos: "verb" },
  { word: "teach", meaning: "教える", pos: "verb" },
  { word: "help", meaning: "助ける", pos: "verb" },
  { word: "make", meaning: "作る", pos: "verb" },
  { word: "use", meaning: "使う", pos: "verb" },
  { word: "open", meaning: "開ける", pos: "verb" },
  { word: "close", meaning: "閉める", pos: "verb" },
  { word: "start", meaning: "始める", pos: "verb" },
  { word: "finish", meaning: "終える", pos: "verb" },
  { word: "like", meaning: "好き", pos: "verb" },
  { word: "love", meaning: "大好き", pos: "verb" },
  { word: "want", meaning: "ほしい", pos: "verb" },
  { word: "need", meaning: "必要とする", pos: "verb" },
  { word: "know", meaning: "知っている", pos: "verb" },
  { word: "think", meaning: "考える", pos: "verb" },
  { word: "work", meaning: "働く／作業する", pos: "verb" },
  { word: "sleep", meaning: "ねる", pos: "verb" },
  { word: "wake", meaning: "起きる", pos: "verb" },
  { word: "swim", meaning: "泳ぐ", pos: "verb" },

  // ===== adjective（30）=====
  { word: "big", meaning: "大きい", pos: "adjective" },
  { word: "small", meaning: "小さい", pos: "adjective" },
  { word: "long", meaning: "長い", pos: "adjective" },
  { word: "short", meaning: "短い", pos: "adjective" },
  { word: "new", meaning: "新しい", pos: "adjective" },
  { word: "old", meaning: "古い", pos: "adjective" },
  { word: "good", meaning: "良い", pos: "adjective" },
  { word: "bad", meaning: "悪い", pos: "adjective" },
  { word: "easy", meaning: "やさしい", pos: "adjective" },
  { word: "difficult", meaning: "むずかしい", pos: "adjective" },
  { word: "happy", meaning: "うれしい", pos: "adjective" },
  { word: "sad", meaning: "かなしい", pos: "adjective" },
  { word: "busy", meaning: "いそがしい", pos: "adjective" },
  { word: "free", meaning: "ひまな", pos: "adjective" },
  { word: "fast", meaning: "速い", pos: "adjective" },
  { word: "slow", meaning: "おそい", pos: "adjective" },
  { word: "hot", meaning: "暑い", pos: "adjective" },
  { word: "cold", meaning: "寒い", pos: "adjective" },
  { word: "warm", meaning: "あたたかい", pos: "adjective" },
  { word: "cool", meaning: "すずしい", pos: "adjective" },
  { word: "tall", meaning: "背が高い", pos: "adjective" },
  { word: "shorter", meaning: "より短い", pos: "adjective" },
  { word: "strong", meaning: "強い", pos: "adjective" },
  { word: "weak", meaning: "弱い", pos: "adjective" },
  { word: "clean", meaning: "きれいな", pos: "adjective" },
  { word: "dirty", meaning: "よごれた", pos: "adjective" },
  { word: "early", meaning: "早い", pos: "adjective" },
  { word: "late", meaning: "おそい（時間）", pos: "adjective" },
  { word: "hungry", meaning: "おなかがすいた", pos: "adjective" },
  { word: "thirsty", meaning: "のどがかわいた", pos: "adjective" },

  // ===== preposition（20）=====
  { word: "in", meaning: "〜の中に", pos: "preposition" },
  { word: "on", meaning: "〜の上に", pos: "preposition" },
  { word: "under", meaning: "〜の下に", pos: "preposition" },
  { word: "over", meaning: "〜の上を", pos: "preposition" },
  { word: "by", meaning: "〜のそばに", pos: "preposition" },
  { word: "near", meaning: "〜の近くに", pos: "preposition" },
  { word: "with", meaning: "〜といっしょに", pos: "preposition" },
  { word: "without", meaning: "〜なしで", pos: "preposition" },
  { word: "for", meaning: "〜のために", pos: "preposition" },
  { word: "from", meaning: "〜から", pos: "preposition" },
  { word: "to", meaning: "〜へ", pos: "preposition" },
  { word: "at", meaning: "〜で", pos: "preposition" },
  { word: "into", meaning: "〜の中へ", pos: "preposition" },
  { word: "out", meaning: "外へ", pos: "preposition" },
  { word: "about", meaning: "〜について", pos: "preposition" },
  { word: "before", meaning: "〜の前に", pos: "preposition" },
  { word: "after", meaning: "〜の後に", pos: "preposition" },
  { word: "between", meaning: "〜の間に", pos: "preposition" },
  { word: "behind", meaning: "〜の後ろに", pos: "preposition" },
  { word: "around", meaning: "〜のまわりに", pos: "preposition" },
];
